import type { StrategyRules } from "./types";

export function generatePineScript(rules: StrategyRules) {
  const session = rules.sessionTime.replace(":", "");
  return `//@version=5
strategy("${rules.name}", overlay=true, pyramiding=0, commission_type=strategy.commission.percent, commission_value=${rules.fees ? "0.01" : "0"})

// Generated by EdgeLab from the exact tested rules.
// Results may differ due to data, session handling, fees, slippage, and fill rules.
orbMinutes = input.int(${rules.openingRangeMinutes}, "Opening range minutes")
rewardRisk = input.float(${rules.rewardRisk}, "Reward / risk")
sessionStart = input.session("${session}-${session}", "Session start")
newSession = not na(time(timeframe.period, sessionStart, "${rules.timezone}"))
var float rangeHigh = na
var float rangeLow = na
var int sessionBar = 0

if newSession and not newSession[1]
    rangeHigh := high
    rangeLow := low
    sessionBar := 1
else if sessionBar > 0 and sessionBar * timeframe.multiplier < orbMinutes
    rangeHigh := math.max(rangeHigh, high)
    rangeLow := math.min(rangeLow, low)
    sessionBar += 1

rangeReady = sessionBar * timeframe.multiplier >= orbMinutes
risk = rangeHigh - rangeLow
if rangeReady and ta.crossover(high, rangeHigh)${rules.direction === "short_only" ? " and false" : ""}
    strategy.entry("Long", strategy.long)
    strategy.exit("Long exit", "Long", stop=rangeLow, limit=rangeHigh + risk * rewardRisk)
if rangeReady and ta.crossunder(low, rangeLow)${rules.direction === "long_only" ? " and false" : ""}
    strategy.entry("Short", strategy.short)
    strategy.exit("Short exit", "Short", stop=rangeHigh, limit=rangeLow - risk * rewardRisk)
`;
}

export function downloadText(filename: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
